# Generated by Django 5.0.4 on 2024-05-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="stars",
            field=models.IntegerField(null=True),
        ),
    ]
