# Generated by Django 5.0.4 on 2024-05-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_offer_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="stars",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
