# Generated by Django 5.0.4 on 2024-05-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_offer_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="license",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
