# Generated by Django 5.0.4 on 2024-05-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_vehicle_license"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="stars",
            new_name="stars_to_user",
        ),
    ]
