# Generated by Django 5.0.4 on 2024-05-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_stars_offer_stars_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="stars_to_driver",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
