# Generated by Django 5.0.4 on 2024-05-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_offer_stars_to_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="finished_by",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
