# Generated by Django 5.0.4 on 2024-08-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_offer_passenger_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(default="car", max_length=255),
            preserve_default=False,
        ),
    ]
