# Generated by Django 5.0.4 on 2024-05-01 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_offer_passenger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="passenger",
                to="core.offer",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="current_trip_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver",
                to="core.trip",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="currently_driver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="currently_passenger",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(default="M", max_length=1),
        ),
        migrations.AddField(
            model_name="user",
            name="rating_driver",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="rating_passenger",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="total_stars_driver",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="total_stars_passenger",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="total_trips_driver",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="total_trips_passenger",
            field=models.IntegerField(default=0),
        ),
    ]
